mysql:
  host: 127.0.0.1
  port: 3306
  db: blog
  user: root
  password: 123456
  logLevel: dev

# docker run --name myredis -p 6379:6379 -d redis --requirepass "test123456"
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: test123456
  pool-size: 20

logger:
  level: info
#  level: warning
  prefix: "go-blog"
  director: log
  show-line: true
  log-in-console: true
  logger-file-path: "data/logs"

system:
  host: "0.0.0.0"
  port: 8888
  env: debug
  login-limit-time: 30 # minute
  login-limit-count: 4
jwt:
  sign-key: gin-demo
  expired-time: 1d
  buffer-time: 6h
  issuser: gin-demo